spring.application.name=HCM-K24-CNTT1_PhamCongThanh_002

spring.datasource.url=jdbc:h2:mem:geardb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

logging.level.root=INFO
logging.level.com.example.hcmk24cntt1_phamcongthanh_002.controller=DEBUG
logging.level.com.example.hcmk24cntt1_phamcongthanh_002.service=DEBUG
logging.pattern.console=%d{HH:mm:ss} [%level] %logger{36} - %msg%n
